#!/bin/bash

WWWROOT=/var/www/html
# maintain backwards compatibility
if [ -f /etc/xsce/xsce.env ]; then
  source /etc/xsce/xsce.env
fi
if [ -f /etc/iiab/iiab.env ]; then
  source /etc/iiab/iiab.env
fi

############  temporary code to put old and new menues side by side #####
DEMODIR=$WWWROOT/home/demo
mkdir -p $DEMODIR
# copy sample index file if none exists in home
if [ ! -e $WWWROOT/home/index.html ]; then
    cp samples/db-sampler.html $DEMODIR/index.html
fi
#########################################################################

MENUDIR=$WWWROOT/iiab-menu
mkdir -p $MENUDIR

mkdir -p $MENUDIR/local/menu-defs
mkdir -p $MENUDIR/local/html
mkdir -p $MENUDIR/local/unedited

# copy changed files to local if this is not the first time
if [ -f $MENUDIR/menu-defs.lst ]; then
  # record timestamp and size of changed set of files
  TZ=utc ls -l --time-style=full-iso $MENUDIR/menu-files/menu-defs/*.{json,html} |awk '{print $5" "$6":"$7" "$9}' >$MENUDIR/changed-menu-defs.lst
  TZ=utc ls -l --time-style=full-iso $MENUDIR/menu-files/html/*.html |awk '{print $5" "$6":"$7" "$9}' >$MENUDIR/changed-html.lst
  ./bu-local $MENUDIR
fi

rsync -av common $WWWROOT
rsync -av menu-files $MENUDIR
rsync -av samples $MENUDIR

# refresh kiwix zim index
iiab-make-kiwix-lib

# copy iiab-meter service to web root
cp -f menu-files/services/iiab_meter.php $WWWROOT

# copy config file if none exists
if [ ! -e $MENUDIR/config.json ]; then
    cp config.json $MENUDIR
fi

# copy sample index file if none exists
if [ ! -e $MENUDIR/index.html ]; then
    cp samples/sampler.html $MENUDIR/index.html
fi

# copy sample index file if none exists in home
if [ ! -e $WWWROOT/home/index.html ]; then
    cp samples/sampler.html $WWWROOT/home/index.html
fi

# restore modified files from local
cp -rf $MENUDIR/local/* $MENUDIR/menu-files

echo 'files copied'

# record timestamp and size of current set of files
TZ=utc ls -l --time-style=full-iso $MENUDIR/menu-files/menu-defs/*.{json,html} |awk '{print $5" "$6":"$7" "$9}' >$MENUDIR/menu-defs.lst
TZ=utc ls -l --time-style=full-iso $MENUDIR/menu-files/html/*.html |awk '{print $5" "$6":"$7" "$9}' >$MENUDIR/html.lst

# Check for user and create if absent
rc=`mysql --execute "SELECT Password FROM mysql.user where Host = 'localhost' and User = 'iiab_commenter';"`

if [ "$rc" = "" ]; then
  mysql --execute "CREATE USER iiab_commenter@localhost IDENTIFIED BY 'g0adm1n';"
fi

# Create database and table
mysql < setup/comments-db.sql

#################  additions for fetching menu items from mysql #########
# Check for user and create if absent
rc=`mysql --execute "SELECT Password FROM mysql.user where Host = 'localhost' and User = 'menus_user';"`

if [ "$rc" = "" ]; then
  mysql --execute "CREATE USER menus_user@localhost IDENTIFIED BY 'g0adm1n';"
fi

# start populating the menus_db
mysql --execute "CREATE DATABASE if NOT exists 'menus_db';"

mysql < languages.sql
mysql < menus-db.sql

$MENUSDIR/setup/defs-migrate.py
echo 'database created'
