#!/bin/bash -x

if [ -f /etc/iiab/iiab.env ]
then
  . /etc/iiab/iiab.env
else
 echo "IIAB Config not found."
 echo "Please install Internet in a Box before installing the Admin Console."
 echo "Exiting."
 exit
fi

# facts file for admin console, assumes iiab created directory
cp ./scripts/admin_facts.fact /etc/ansible/facts.d/admin_facts.fact

PLAYBOOK="install-menus.yml"
INVENTORY="ansible_hosts"

MENUS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -f $MENUS_DIR/$PLAYBOOK ]; then
 echo "Admin Console Playbook not found."
 echo "Please make sure you have cloned the iiab-admin git repo."
 echo "Exiting."
 exit
fi

cd $MENUS_DIR

echo "Running local playbooks! "


export ANSIBLE_LOG_PATH="$MENUS_DIR/menus-install.log"

#ansible-playbook -i $INVENTORY $PLAYBOOK --extra-vars "${ARGS}" --connection=local
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
